add new options for opensearch 3.x
Note that security manager was deprecated in 3.0 and (apparently)
removed in at least 3.4.

https://opensearch.org/blog/finding-a-replacement-for-jsm-in-opensearch-3-0/

Enabling this in 3.4 gives the error:

    java.lang.Error: A command line option has attempted to allow or enable the Security Manager. Enabling a Security Manager is not supported.